/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5Qp2zvzpw3y
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Crimson_Text } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { useEffect } from "react";
import { useState } from "react";
import service from "backend/config";



export function ProductListing() {
  const [products, setProducts] = useState([])

  useEffect(()=>{
    try {

      const fetchData = async()=>{
        const response = await service.getProductList()
        console.log("App :: response :: ", response.data.data.products);
        setProducts (response.data.data.products)
        console.log("the final products are",products)
        console.log("done")
      }

      fetchData()
      
    } catch (error) {
      console.log("App :: error :: ", error);
    }
  },[])



  return (
    (<div className="flex flex-col">
      <section className="bg-muted py-12 md:py-20">
        <div className="container grid md:grid-cols-2 gap-8 items-center">
          <div>
            <img
              src="/placeholder.svg"
              alt="Book Cover"
              width={400}
              height={600}
              className="rounded-lg shadow-lg" />
          </div>
          <div className="space-y-4">
            <h1 className="text-3xl md:text-4xl font-bold">The Art of Coding: A Beginner's Guide</h1>
            <p className="text-muted-foreground text-lg">By Jane Doe</p>
            <div className="flex items-center gap-2">
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
              <span className="text-muted-foreground text-sm">(4.2)</span>
            </div>
            <p className="text-2xl font-bold">$24.99</p>
            <Button size="lg">Add to Cart</Button>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container">
          <div className="grid gap-8">
            <div>
              <h2 className="text-2xl md:text-3xl font-bold mb-4">About the Book</h2>
              <p className="text-muted-foreground text-lg leading-relaxed">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl nec ultricies ultricies, nunc
                nisl ultricies nunc, nec ultricies nunc nisl nec nunc. Nullam auctor, nisl nec ultricies ultricies, nunc
                nisl ultricies nunc, nec ultricies nunc nisl nec nunc.
              </p>
            </div>
            <div>
              <h2 className="text-2xl md:text-3xl font-bold mb-4">Customer Reviews</h2>
              <div className="space-y-8">
                <div className="flex gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <h3 className="font-semibold">Sarah Johnson</h3>
                      <div className="flex items-center gap-0.5">
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                        <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      </div>
                    </div>
                    <p className="text-muted-foreground">
                      This book is a great introduction to coding for beginners. The author explains concepts clearly
                      and provides practical examples.
                    </p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <h3 className="font-semibold">Alex Smith</h3>
                      <div className="flex items-center gap-0.5">
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      </div>
                    </div>
                    <p className="text-muted-foreground">
                      I highly recommend this book to anyone interested in learning to code. The author's teaching style
                      is engaging and the content is well-structured.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <h2 className="text-2xl md:text-3xl font-bold mb-4">Related Products</h2>
              <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8">
                <div className="group">
                  <a  className="block" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      alt="Book Cover"
                      width={300}
                      height={400}
                      className="rounded-lg shadow-lg group-hover:opacity-80 transition-opacity" />
                  </a>
                  <div className="mt-4 space-y-2">
                    <h3 className="text-lg font-semibold">Mastering JavaScript: A Comprehensive Guide</h3>
                    <p className="text-muted-foreground">By John Doe</p>
                    <p className="text-lg font-bold">$29.99</p>
                    <Button variant="outline" size="sm">
                      Add to Cart
                    </Button>
                  </div>
                </div>
               
              { products &&
                  products.map((product)=>{

<div key={product._id} className="group">
                  <a  className="block" prefetch={false}>
                    <img
                      src={product.mainImage.url}
                      alt="Book Cover"
                      width={300}
                      height={400}
                      className="rounded-lg shadow-lg group-hover:opacity-80 transition-opacity" />
                  </a>
                  <div className="mt-4 space-y-2">
                    <h3 className="text-lg font-semibold">Mastering JavaScript: A Comprehensive Guide</h3>
                    <p className="text-muted-foreground">By John Doe</p>
                    <p className="text-lg font-bold">$29.99</p>
                    <Button variant="outline" size="sm">
                      Add to Cart
                    </Button>
                  </div>
                </div>
                    

                  })
                }
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>)
  );
}

function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
